runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /.*
  script: main.app

libraries:
- name: MySQLdb
  version: "latest"
- name: django
  version: "1.4"
env_variables:
    CLOUDSQL_CONNECTION_NAME: "your gcloud sql instance follwed by your project name"
    CLOUDSQL_USER: "your gcloud sql username"
    CLOUDSQL_PASSWORD: "yor gcloud sql password"
    CLOUDSQL_DATABASE: "your gcloud sql database name"
